#ifndef _const_H
#define _const_H
enum type_of_lex 
{
    LEX_NULL, //0
    LEX_AND, LEX_BEGIN, LEX_BOOL,LEX_DO,LEX_ELSE,LEX_END,LEX_IF,
    LEX_FALSE,LEX_INT,LEX_NOT,LEX_OR,LEX_PROGRAM,LEX_READ,LEX_THEN,
    LEX_TRUE,LEX_VAR,LEX_WHILE,LEX_WRITE, //18 //добавить лексем еще?
    LEX_FIN, //19
    LEX_COLON,LEX_ASSIGN,LEX_LPAREN,LEX_RPAREN,
    LEX_EQ,LEX_LSS,LEX_GTR,LEX_PLUS,LEX_MINUS,LEX_TIMES,LEX_SLASH,LEX_LEQ,LEX_NEQ,
    LEX_SEMICOLON, LEX_COMMA, LEX_GEQ, //35
    LEX_NUM, //36
    LEX_ID, //37
    POLIZ_LABEL, //38
    POLIZ_ADDRESS, //39
    POLIZ_GO, //40
    POLIZ_FGO //41
}; 

#endif //_const_H